name: asset_gen
description: Generate a Dart class containing constant paths for all assets in your Flutter app.
version: 1.0.1-beta.1
homepage: https://github.com/ravi84184/asset_gen
repository: https://github.com/ravi84184/asset_gen

executables:
  asset_gen: asset_gen

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
